apiVersion: v1
kind: Secret
metadata:
    name: kerberos-keytab-secret
type: Opaque
data:
    user: ENC[AES256_GCM,data:m12yJGpHz5YHr6teGcZ0OHSqexU=,iv:xgjGVM1CKlL/Zerlts/iHcDUUMp+u9NPmQdR1CVBmTE=,tag:NpBUyVYFnb4lxGMNQE8lug==,type:str]
    keytab: ENC[AES256_GCM,data:O4Bl47WMcGFplQtkZiPIZm/L1fGdC70e9O47JvcqxdvuY3phkVaYuqOU30UGqUj3NzyIps/xrxIi81h4YOz6QZcP2Uv69phzApKK2mqZ6YCIphfftGkyf4hSIDL1Lz7p06NBlZpbpUv0LIcjqZRg/Qn8mtnFqwXGDHzE9wMG7pSZFaE1dC2aa/S6Vc8Z7GUOoKCdzhpKOeWyuM4b18h70xZi/RbXM33qWXbeQcRpwKA=,iv:E5gRyAxMSxfx8/8sbeDNR1WgJc+oxfkuwvofT8LvSgg=,tag:OsJwLK3SCVRKO2Qjfiqf1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    barbican:
    -   secret_href: https://openstack.cern.ch:9311/v1/secrets/c4440a31-5483-458d-aaf2-566d1fdf73d2
        created_at: '2020-10-14T00:03:25Z'
        enc: AJ8Wnbft5T1QavGs4wnCAsk6plxnwCE2ErOANnWA5nOe6P3a0brbg2WbFCSQuaoB
    lastmodified: '2020-10-14T00:03:27Z'
    mac: ENC[AES256_GCM,data:WaDSTPQ18Nabekmny0jhUevYURQD8+ZtzSh8USG1CpZoXjsZGG94yjAhzFaS/9iCxZXrpikl1OMMBjRb2vU9pFtGws4IhpsdFwvEqagGYHkKvvKu7oep7EkCEvIACkTQO5sTmrjUQVv7ONyygVTBlsOKeOYp6ErpH9b20xpvFQk=,iv:7qBi6bNaTze5o8zlvTdj/S2YWqUsRzaXdkUgcowke8g=,tag:5qMi60wOwgXjn4TkwADVzQ==,type:str]
    pgp: []
    encrypted_regex: ^(user)|(.*key.*)$
    version: 3.6.1
