apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install/?ref=stable

patchesStrategicMerge:
- overlays/production/argocd-cm-kustomize-alpha-plugins-patch.yaml
- overlays/production/argocd-repo-server-ksops-patch.yaml
