apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  # Delete resources when deleting app
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.cern.ch/clange/gitops-argo-cd.git
    targetRevision: HEAD
    path: 04_secrets-argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd