apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo/manifests/cluster-install/?ref=stable
- base/workflow-rbac.yaml
- base/cephfs-sc.yaml
- base/cephfs-pvc.yaml

patchesStrategicMerge:
- overlays/production/workflow-controller-spec-security-patch.yaml